# Generated by Django 6.0.6 on 2026-06-07 21:53

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Document type')),
                ('file', models.FileField(upload_to='order_docs/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Order document',
                'verbose_name_plural': 'Order documents',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('at_warehouse', 'At warehouse'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Order status history',
                'verbose_name_plural': 'Order status histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=apps.orders.models.generate_tracking_number, max_length=20, unique=True, verbose_name='Tracking number')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Sender name')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Sender phone')),
                ('sender_address_detail', models.CharField(blank=True, max_length=500, verbose_name='Sender address detail')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Recipient phone')),
                ('recipient_address_detail', models.CharField(blank=True, max_length=500, verbose_name='Recipient address detail')),
                ('cargo_description', models.TextField(verbose_name='Cargo description')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume (m³)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height (cm)')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Declared value')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('at_warehouse', 'At warehouse'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Estimated delivery')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Actual delivery')),
                ('additional_services', models.ManyToManyField(blank=True, to='services.additionalservice', verbose_name='Additional services')),
                ('recipient_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_orders', to='geo.city', verbose_name='Recipient city')),
                ('sender_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_orders', to='geo.city', verbose_name='Sender city')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
