# Generated by Django 6.0.6 on 2026-06-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Recipient email'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sender email'),
        ),
    ]
