# Generated by Django 6.0.6 on 2026-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_extend_status_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='file',
            field=models.FileField(upload_to='uploads/order_docs/', verbose_name='File'),
        ),
    ]
