# Generated by Django 6.0.6 on 2026-06-09 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
