# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderstatushistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Fragile cargo'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Dangerous goods'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_temperature_sensitive',
            field=models.BooleanField(default=False, verbose_name='Temperature-sensitive cargo'),
        ),
    ]
