# Generated by Django 6.0.6 on 2026-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_fragile_dangerous_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('awaiting_delivery_to_branch', 'Awaiting delivery to branch'), ('available_in_warehouse', 'Available in warehouse'), ('awaiting_courier', 'Awaiting courier'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('customs_clearance', 'Customs clearance'), ('at_warehouse', 'At warehouse'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('awaiting_delivery_to_branch', 'Awaiting delivery to branch'), ('available_in_warehouse', 'Available in warehouse'), ('awaiting_courier', 'Awaiting courier'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('customs_clearance', 'Customs clearance'), ('at_warehouse', 'At warehouse'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=40, verbose_name='Status'),
        ),
    ]
