# Generated by Django 6.0.6 on 2026-06-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_unit', 'Per unit'), ('percentage', 'Percentage')], default='fixed', max_length=20, verbose_name='Price type')),
            ],
            options={
                'verbose_name': 'Additional service',
                'verbose_name_plural': 'Additional services',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min weight (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max weight (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per kg')),
                ('delivery_days_min', models.IntegerField(verbose_name='Min delivery days')),
                ('delivery_days_max', models.IntegerField(verbose_name='Max delivery days')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.servicecategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Service category',
                'verbose_name_plural': 'Service categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base price')),
                ('price_unit', models.CharField(blank=True, max_length=50, verbose_name='Price unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
