# Generated by Django 6.0.6 on 2026-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short description (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
    ]
