# Generated by Django 6.0.6 on 2026-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_additionalservice_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='is_door_service',
            field=models.BooleanField(default=False, verbose_name='Door-to-door service'),
        ),
    ]
