# Generated by Django 6.0.6 on 2026-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_additionalservice_is_door_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
