# Generated by Django 6.0.6 on 2026-06-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('page_type', models.CharField(choices=[('about', 'About'), ('news', 'News'), ('vacancy', 'Vacancy'), ('review', 'Review'), ('press', 'Press'), ('tender', 'Tender'), ('faq', 'FAQ')], max_length=20, verbose_name='Page type')),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('question_en', models.CharField(blank=True, max_length=500, verbose_name='Question (EN)')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer (EN)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_text', models.TextField(verbose_name='Short text')),
                ('short_text_en', models.TextField(blank=True, verbose_name='Short text (EN)')),
                ('full_text', models.TextField(verbose_name='Full text')),
                ('full_text_en', models.TextField(blank=True, verbose_name='Full text (EN)')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Image')),
                ('published_at', models.DateTimeField(verbose_name='Published at')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('full_description', models.TextField(verbose_name='Full description')),
                ('image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='Image')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Author name')),
                ('author_company', models.CharField(blank=True, max_length=255, verbose_name='Author company')),
                ('text', models.TextField(verbose_name='Text')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('full_description', models.TextField(verbose_name='Full description')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary from')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary to')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-published_at'],
            },
        ),
    ]
