# Generated by Django 6.0.6 on 2026-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned to homepage'),
        ),
    ]
