# Generated by Django 6.0.6 on 2026-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/promotions/', verbose_name='Image'),
        ),
    ]
