# Generated by Django 6.0.6 on 2026-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Document type')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fulfilled at')),
            ],
            options={
                'verbose_name': 'Accounting request',
                'verbose_name_plural': 'Accounting requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('category', models.CharField(choices=[('contracts', 'Contracts'), ('shipping_docs', 'Shipping documents'), ('receipt_docs', 'Receipt documents'), ('power_of_attorney', 'Power of attorney'), ('charter', 'Charter'), ('claims', 'Claims'), ('refunds', 'Refunds'), ('tue_replacement', 'TUE replacement')], max_length=30, verbose_name='Category')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['category', 'title'],
            },
        ),
    ]
