# Generated by Django 6.0.6 on 2026-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingrequest',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('act', 'Certificate of Completion'), ('receipt', 'Receipt'), ('other', 'Other')], max_length=100, verbose_name='Document type'),
        ),
    ]
