# Generated by Django 6.0.6 on 2026-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_accountingrequest_document_type'),
        ('services', '0004_additionalservice_tariff_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='documents', to='services.additionalservice', verbose_name='Additional services'),
        ),
        migrations.AddField(
            model_name='document',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='documents', to='services.service', verbose_name='Services'),
        ),
    ]
