# Generated by Django 6.0.6 on 2026-06-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_add_contact_delivery_templates'),
        ('services', '0003_additionalservice_is_door_service'),
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatars/', verbose_name='Avatar'),
        ),
        migrations.CreateModel(
            name='ContactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template name')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Recipient phone')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Recipient email')),
                ('address_detail', models.CharField(blank=True, max_length=500, verbose_name='Address detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city', verbose_name='City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact template',
                'verbose_name_plural': 'Contact templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template name')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Cargo description')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Declared value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('from_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_template_from', to='geo.city', verbose_name='From city')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Service')),
                ('to_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_template_to', to='geo.city', verbose_name='To city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Delivery template',
                'verbose_name_plural': 'Delivery templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
