# Generated by Django 6.0.6 on 2026-06-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_contact_delivery_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttemplate',
            name='template_type',
            field=models.CharField(choices=[('sender', 'Sender'), ('recipient', 'Recipient')], default='recipient', max_length=20, verbose_name='Template type'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_phone',
            field=models.CharField(max_length=20, verbose_name='Contact phone'),
        ),
    ]
