# Generated by Django 6.0.6 on 2026-06-09 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_template_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template name')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Cargo description')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Length (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Width (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Height (cm)')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Declared value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cargo template',
                'verbose_name_plural': 'Cargo templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
