# Generated by Django 6.0.6 on 2026-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_additionalservice_is_door_service'),
        ('users', '0005_cargotemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytemplate',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.additionalservice', verbose_name='Additional services'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='recipient_address_detail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recipient address detail'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='sender_address_detail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sender address detail'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total price'),
        ),
    ]
