# Generated by Django 6.0.6 on 2026-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_delivery_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytemplate',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Width (cm)'),
        ),
    ]
