# Generated by Django 6.0.6 on 2026-06-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_deliverytemplate_height_deliverytemplate_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDirectoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(choices=[('cities', 'Cities'), ('branches', 'Branches'), ('services', 'Services'), ('service_categories', 'Service categories'), ('additional_services', 'Additional services'), ('tariffs', 'Tariffs'), ('documents', 'Documents'), ('faq', 'FAQ'), ('news', 'News'), ('vacancies', 'Vacancies'), ('promotions', 'Promotions'), ('banners', 'Banners'), ('reviews', 'Reviews'), ('content_pages', 'Content pages'), ('orders', 'Orders'), ('tickets', 'Tickets'), ('partner_applications', 'Partner applications')], max_length=50, verbose_name='Directory')),
                ('can_access', models.BooleanField(default=False, verbose_name='Can access')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='directory_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Manager directory permission',
                'verbose_name_plural': 'Manager directory permissions',
                'ordering': ['manager', 'directory'],
                'unique_together': {('manager', 'directory')},
            },
        ),
    ]
