# Generated by Django 6.0.6 on 2026-06-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_city_country'),
        ('services', '0004_additionalservice_tariff_is_active'),
        ('users', '0009_companyapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttemplate',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='contacttemplate',
            name='city',
        ),
        migrations.AddField(
            model_name='cargotemplate',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Dangerous goods'),
        ),
        migrations.AddField(
            model_name='cargotemplate',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Fragile cargo'),
        ),
        migrations.AddField(
            model_name='cargotemplate',
            name='is_temperature_sensitive',
            field=models.BooleanField(default=False, verbose_name='Temperature-sensitive cargo'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='recipient_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_contact_templates', to='geo.city', verbose_name='Recipient city'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='recipient_address_detail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recipient address detail'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='sender_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_contact_templates', to='geo.city', verbose_name='Sender city'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='sender_address_detail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sender address detail'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sender email'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sender name'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sender phone'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Dangerous goods'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Fragile cargo'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='is_temperature_sensitive',
            field=models.BooleanField(default=False, verbose_name='Temperature-sensitive cargo'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Recipient email'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recipient name'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Recipient phone'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sender email'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sender name'),
        ),
        migrations.AddField(
            model_name='deliverytemplate',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sender phone'),
        ),
        migrations.AlterField(
            model_name='cargotemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Recipient email'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recipient name'),
        ),
        migrations.AlterField(
            model_name='contacttemplate',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Recipient phone'),
        ),
        migrations.AlterField(
            model_name='deliverytemplate',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_template_from', to='geo.city', verbose_name='From city'),
        ),
        migrations.AlterField(
            model_name='deliverytemplate',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='deliverytemplate',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_template_to', to='geo.city', verbose_name='To city'),
        ),
        migrations.AlterField(
            model_name='deliverytemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight (kg)'),
        ),
    ]
