# Generated by Django 6.0.6 on 2026-06-21 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rework_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargotemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cargo template (deprecated)', 'verbose_name_plural': 'Cargo templates (deprecated)'},
        ),
        migrations.AlterField(
            model_name='cargotemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_templates_deprecated', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='managerdirectorypermission',
            name='directory',
            field=models.CharField(choices=[('cities', 'Cities'), ('branches', 'Branches'), ('services', 'Services'), ('service_categories', 'Service categories'), ('additional_services', 'Additional services'), ('tariffs', 'Tariffs'), ('documents', 'Documents'), ('faq', 'FAQ'), ('news', 'News'), ('vacancies', 'Vacancies'), ('promotions', 'Promotions'), ('banners', 'Banners'), ('reviews', 'Reviews'), ('content_pages', 'Content pages'), ('orders', 'Orders'), ('tickets', 'Tickets'), ('partner_applications', 'Partner applications'), ('partners', 'Partners')], max_length=50, verbose_name='Directory'),
        ),
        migrations.AlterModelTable(
            name='deliverytemplate',
            table='users_deliverytemplate',
        ),
    ]
