from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('login/', views.DashboardLoginView.as_view(), name='login'),
    path('', views.DashboardHomeView.as_view(), name='home'),
    path('users/', views.DashboardUsersView.as_view(), name='users'),
    path('users/create/', views.DashboardUserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', views.DashboardUserUpdateView.as_view(), name='user_edit'),
    path('users/<int:pk>/delete/', views.DashboardUserDeleteView.as_view(), name='user_delete'),
    path('orders/', views.DashboardOrdersView.as_view(), name='orders'),
    path('orders/<int:pk>/', views.DashboardOrderDetailView.as_view(), name='order_detail'),
    path('orders/<int:pk>/edit/', views.DashboardOrderUpdateView.as_view(), name='order_edit'),
    path('orders/<int:pk>/delete/', views.DashboardOrderDeleteView.as_view(), name='order_delete'),
    path('tickets/', views.DashboardTicketsView.as_view(), name='tickets'),
    path('services/', views.DashboardServicesView.as_view(), name='services'),
    path('services/create/', views.DashboardServiceCreateView.as_view(), name='service_create'),
    path('services/<int:pk>/edit/', views.DashboardServiceUpdateView.as_view(), name='service_edit'),
    path('services/<int:pk>/delete/', views.DashboardServiceDeleteView.as_view(), name='service_delete'),
    path('services/categories/create/', views.DashboardServiceCategoryCreateView.as_view(), name='category_create'),
    path('services/categories/<int:pk>/edit/', views.DashboardServiceCategoryUpdateView.as_view(), name='category_edit'),
    path('services/categories/<int:pk>/delete/', views.DashboardServiceCategoryDeleteView.as_view(), name='category_delete'),
    path('services/tariffs/create/', views.DashboardTariffCreateView.as_view(), name='tariff_create'),
    path('services/tariffs/<int:pk>/edit/', views.DashboardTariffUpdateView.as_view(), name='tariff_edit'),
    path('services/tariffs/<int:pk>/delete/', views.DashboardTariffDeleteView.as_view(), name='tariff_delete'),
    path('content/', views.DashboardContentListView.as_view(), name='content'),
    path('content/pages/create/', views.DashboardContentPageCreateView.as_view(), name='content_page_create'),
    path('content/pages/<int:pk>/edit/', views.DashboardContentPageUpdateView.as_view(), name='content_page_edit'),
    path('content/pages/<int:pk>/delete/', views.DashboardContentPageDeleteView.as_view(), name='content_page_delete'),
    path('content/news/create/', views.DashboardNewsCreateView.as_view(), name='news_create'),
    path('content/news/<int:pk>/edit/', views.DashboardNewsUpdateView.as_view(), name='news_edit'),
    path('content/news/<int:pk>/delete/', views.DashboardNewsDeleteView.as_view(), name='news_delete'),
    path('content/vacancies/create/', views.DashboardVacancyCreateView.as_view(), name='vacancy_create'),
    path('content/vacancies/<int:pk>/edit/', views.DashboardVacancyUpdateView.as_view(), name='vacancy_edit'),
    path('content/vacancies/<int:pk>/delete/', views.DashboardVacancyDeleteView.as_view(), name='vacancy_delete'),
    path('content/faqs/create/', views.DashboardFAQCreateView.as_view(), name='faq_create'),
    path('content/faqs/<int:pk>/edit/', views.DashboardFAQUpdateView.as_view(), name='faq_edit'),
    path('content/faqs/<int:pk>/delete/', views.DashboardFAQDeleteView.as_view(), name='faq_delete'),
    path('content/reviews/create/', views.DashboardReviewCreateView.as_view(), name='review_create'),
    path('content/reviews/<int:pk>/edit/', views.DashboardReviewUpdateView.as_view(), name='review_edit'),
    path('content/reviews/<int:pk>/delete/', views.DashboardReviewDeleteView.as_view(), name='review_delete'),
    path('content/tenders/create/', views.DashboardTenderCreateView.as_view(), name='tender_create'),
    path('content/tenders/<int:pk>/edit/', views.DashboardTenderUpdateView.as_view(), name='tender_edit'),
    path('content/tenders/<int:pk>/delete/', views.DashboardTenderDeleteView.as_view(), name='tender_delete'),
    path('branches/', views.DashboardBranchesView.as_view(), name='branches'),
    path('branches/create/', views.DashboardBranchCreateView.as_view(), name='branch_create'),
    path('branches/<int:pk>/edit/', views.DashboardBranchUpdateView.as_view(), name='branch_edit'),
    path('branches/<int:pk>/delete/', views.DashboardBranchDeleteView.as_view(), name='branch_delete'),
    path('documents/', views.DashboardDocumentsView.as_view(), name='documents'),
    path('partners/', views.DashboardPartnersView.as_view(), name='partners'),
    path('partners/applications/<int:pk>/edit/', views.DashboardPartnerApplicationUpdateView.as_view(), name='partner_application_edit'),
    path('partners/applications/<int:pk>/delete/', views.DashboardPartnerApplicationDeleteView.as_view(), name='partner_application_delete'),
    path('partners/banners/create/', views.DashboardBannerCreateView.as_view(), name='banner_create'),
    path('partners/banners/<int:pk>/edit/', views.DashboardBannerUpdateView.as_view(), name='banner_edit'),
    path('partners/banners/<int:pk>/delete/', views.DashboardBannerDeleteView.as_view(), name='banner_delete'),
    path('contacts/', views.DashboardContactsView.as_view(), name='contacts'),
    path('settings/', views.DashboardSettingsView.as_view(), name='settings'),
]