# Generated by Django 6.0.6 on 2026-06-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('pickup_point', 'Pickup point'), ('office', 'Office')], max_length=20, verbose_name='Branch type')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('address_en', models.CharField(blank=True, max_length=500, verbose_name='Address (EN)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Working hours')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('has_pickup', models.BooleanField(default=False, verbose_name='Pickup available')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Delivery available')),
                ('has_loading_equipment', models.BooleanField(default=False, verbose_name='Loading equipment')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (EN)')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Region')),
                ('region_en', models.CharField(blank=True, max_length=255, verbose_name='Region (EN)')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branches/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geo.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Branch image',
                'verbose_name_plural': 'Branch images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.city', verbose_name='City'),
        ),
    ]
