# Generated by Django 6.0.6 on 2026-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchimage',
            name='image',
            field=models.ImageField(upload_to='uploads/branches/', verbose_name='Image'),
        ),
    ]
