# Generated by Django 6.0.6 on 2026-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_add_contact_delivery_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
